apiVersion: v1
kind: Service
metadata:
  name: mail-dev
  namespace: livechatting-app
spec:
  selector:
    app: mail-dev
  ports:
    - name: web
      port: 1080
      targetPort: 1080
    - name: smtp
      port: 1025
      targetPort: 1025
  type: ClusterIP