spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/LiveChattingAppDB
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update #only for dev, never in prod
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
      logging:
        level:
          org.springframework.boot.autoconfigure: DEBUG
          org.hibernate.SQL: DEBUG
          org.hibernate.type.descriptor.sql.BasicBinder: TRACE
          com.example.LiveChattingApp: DEBUG
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect


  mail:
    host: localhost
    port: 1025
    username: postgres
    password: pass
    properties:
      mail:
        smtp:
          trust: "*" #never in prod
          auth: true
          starttls: #upgrades plain connection (unencrypted) to encrypted tsl/ssl
            enable: false
            required: false
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000


application:
  security:
    jwt:
      secret-key: OXotaGV4I3puMiMmMCgmJmlxZjJ3bD0wYiRkeXIlOW5vZz12bC1kMDdiMHV3Y2VfPWM= #must be in base 64 to be properly decoded later
      expiration: 8640000  #equivalent to 1 day
  emailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    uploads:
      media-output-path: ./uploads


server:
  servlet:
    context-path: /api/v1/
  address: 0.0.0.0
  port: 8100

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: info,liveness,readiness,health