spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/LiveChattingAppDB
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update #only for dev, never in prod
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
      logging:
        level:
          org.springframework.boot.autoconfigure: DEBUG
          org.hibernate.SQL: DEBUG
          org.hibernate.type.descriptor.sql.BasicBinder: TRACE
          com.example.LiveChattingApp: DEBUG
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/LiveChattingApp
  mail:
    host: localhost
    port: 1025
    username: postgres
    password: pass
    properties:
      mail:
        smtp:
          trust: "*" #never in prod
          auth: true
          starttls: #upgrades plain connection (unencrypted) to encrypted tsl/ssl
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000


application:
  emailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    uploads:
      media-output-path: ./uploads

server:
  port: 8100