apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-app-config
  namespace: livechatting-app
data:
  SPRING_PROFILES_ACTIVE: "dev"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/LiveChattingAppDB"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "pass"
  SPRING_MAIL_HOST: "mail-dev"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: livechatting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:16
          command:
            - sh
            - -c
            - |
              until pg_isready -h postgres -p 5432 -U postgres; do
                echo "Waiting for PostgreSQL..."
                sleep 2
              done
              echo "PostgreSQL is ready!"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      containers:
        - name: spring-app
          image: spring-app-lvc:latest
          imagePullPolicy: Never  # Use local image from minikube
          ports:
            - containerPort: 8100
          envFrom:
            - configMapRef:
                name: spring-app-config
          livenessProbe:
            httpGet:
              path: /api/v1/actuator/health/liveness
              port: 8100
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/v1/actuator/health/readiness
              port: 8100
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: spring-app
  namespace: livechatting-app
spec:
  selector:
    app: spring-app
  ports:
    - port: 8100
      targetPort: 8100
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: spring-app-external
  namespace: livechatting-app
spec:
  selector:
    app: spring-app
  ports:
    - port: 8100
      targetPort: 8100
      nodePort: 30810
  type: NodePort