/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FriendshipResponseDto } from '../../models/friendship-response-dto';

export interface GetSentPendingRequests$Params {
}

export function getSentPendingRequests(http: HttpClient, rootUrl: string, params?: GetSentPendingRequests$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FriendshipResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, getSentPendingRequests.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<FriendshipResponseDto>>;
    })
  );
}

getSentPendingRequests.PATH = '/friendship/sent-pending-requests';
