/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FriendshipRequestDto } from '../../models/friendship-request-dto';
import { FriendshipResponseDto } from '../../models/friendship-response-dto';

export interface SendFriendRequest$Params {
      body: FriendshipRequestDto
}

export function sendFriendRequest(http: HttpClient, rootUrl: string, params: SendFriendRequest$Params, context?: HttpContext): Observable<StrictHttpResponse<FriendshipResponseDto>> {
  const rb = new RequestBuilder(rootUrl, sendFriendRequest.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FriendshipResponseDto>;
    })
  );
}

sendFriendRequest.PATH = '/friendship/request';
