/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateGroupChatRequest {
  description?: string;
  name?: string;
  participantIds?: Array<number>;
}
