/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface Friendship {
  createdAt?: string;
  friend?: User;
  friendshipsStatus?: 'PENDING' | 'ACCEPTED' | 'BLOCKED' | 'REJECTED';
  id?: string;
  user?: User;
}
