/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FriendshipResponseDto {
  createdAt?: string;
  displayName?: string;
  email?: string;
  id?: number;
  requester?: boolean;
  status?: string;
  userId?: string;
}
