/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MessageResponse {
  content?: string;
  createdAt?: string;
  id?: number;
  media?: string;
  mediaFilePath?: string;
  receiverId?: string;
  replyTo?: MessageResponse;
  senderId?: string;
  state?: 'SENT' | 'DELIVERED' | 'READ' | 'FAILED';
  type?: 'JOIN' | 'LEAVE' | 'TEXT' | 'IMAGE' | 'AUDIO' | 'VIDEO';
}
