/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Friendship } from '../models/friendship';
import { GrantedAuthority } from '../models/granted-authority';
import { Role } from '../models/role';
export interface User {
  accountLocked?: boolean;
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  authorities?: Array<GrantedAuthority>;
  createdDate?: string;
  credentialsNonExpired?: boolean;
  dateOfBirth?: string;
  displayName?: string;
  email?: string;
  enabled?: boolean;
  firstname?: string;
  id?: string;
  lastSeenOnline?: string;
  lastSyncTime?: string;
  lastname?: string;
  modifiedDate?: string;
  name?: string;
  password?: string;
  receivedFriendRequests?: Array<Friendship>;
  roles?: Array<Role>;
  sentFriendRequests?: Array<Friendship>;
  userOnline?: boolean;
  username?: string;
}
